### ISSUE TITLE
CCS fails to build against the CC1352R LaunchPad

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc13x2-core#16]
CCS fails to build against the CC1352R LaunchPad when Energia succeeds. 

It seems there is a discrepancy about the floating-point implementation.

> makefile:153: recipe for target 'Blink.out' failed
> c:/users/reivilo/appdata/local/energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: error: Blink.out uses VFP register arguments, c:/users/reivilo/appdata/local/energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/../lib/gcc/arm-none-eabi/8.3.1/thumb/v7e-m/nofp\libgcc.a(_udivmoddi4.o) does not
> c:/users/reivilo/appdata/local/energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: failed to merge target specific data of file c:/users/reivilo/appdata/local/energia15/packages/energia/tools/arm-none-eabi-gcc/8.3.1-20190703/bin/../lib/gcc/arm-none-eabi/8.3.1/thumb/v7e-m/nofp\libgcc.a(_udivmoddi4.o)
> 

## Reference
+ Sketch blink example
+ Windows 10 1909 18363.752
+ CCS  9.3.0.00012 
+ CC13x2 core for Energia 5.29.0-beta2

**Comment by rei-vilo** [comment]
Note: release 5.31.0-beta3 of the CC1352 core for Energia is not recognised by CCS.

**Comment by StefanSch** [comment]
worked for my but i had to close and reopen CCS after installing the newer version

**Comment by StefanSch** [comment]
the link issue can be solved with adding 
-mthumb -mfloat-abi=hard
to the linker options

**Comment by rei-vilo** [comment]
I added it manually to the previous release and forgot to do the same to the new one. Thank you!

**Comment by rei-vilo** [comment]
The `platform.txt` for Energia already contains...

> compiler.c.elf.flags=-O0 -Wl,--gc-sections -specs=nano.specs  -specs=rdimon.specs -specs=nosys.specs -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -static

...but CCS has its own copy of Energia hidden somewhere.

So the latter needs to be updated specifically.

**Comment by rei-vilo** [comment]
But now the Energia CC1352 core has disappeared from CCS.

Luckily, I can rely on embedXcode.
